export { appRouter, type AppRouter } from './router'
export { router, publicProcedure, middleware, mergeRouters } from './trpc'
export type { TrpcContext, TrpcServerDeps, TrpcContextFactory } from './context'
export { startTrpcServer, stopTrpcServer, type StartTrpcServerOpts } from './ws-server'
export { setAppDeps, getAppDeps, setProcessesDeps, getProcessesDeps, setPtyDeps, getPtyDeps, type AppDeps, type ProcessesDeps, type PtyDeps } from './app-deps'
