// Server-side op surface for the tRPC `worktrees` router (transport layer).
// Re-exports the pure git/worktree operations the router wraps — same set the
// legacy `git:*` IPC handlers call. Main-process only (spawns git/gh, touches db).
export {
  isGitRepo,
  detectWorktrees,
  createWorktree,
  removeWorktree,
  runWorktreeSetupScript,
  runWorktreeSetupScriptSync,
  initRepo,
  getCurrentBranch,
  listBranches,
  checkoutBranch,
  createBranch,
  hasUncommittedChanges,
  mergeIntoParent,
  abortMerge,
  startMergeNoCommit,
  isMergeInProgress,
  getConflictedFiles,
  getConflictContent,
  writeResolvedFile,
  commitFiles,
  getWorkingDiff,
  stageFile,
  unstageFile,
  discardFile,
  stageAll,
  unstageAll,
  getFileDiff,
  getUntrackedFileDiff,
  isRebaseInProgress,
  getRebaseProgress,
  abortRebase,
  continueRebase,
  skipRebaseCommit,
  getMergeContext,
  getRecentCommits,
  getAheadBehind,
  getAheadBehindUpstream,
  getStatusSummary,
  getRemoteUrl,
  gitFetch,
  gitPush,
  gitPull,
  getDefaultBranch,
  listBranchesDetailed,
  listRemoteBranches,
  getMergeBase,
  getCommitsSince,
  getCommitsBeforeRef,
  deleteBranch,
  pruneRemote,
  rebaseOnto,
  mergeFrom,
  getDiffStats,
  getWorktreeMetadata,
  getCommitDag,
  resolveChildBranches,
  copyIgnoredFiles,
  getIgnoredFileTree,
  initSubmodules,
  initSubmodulesSync,
  getResolvedCommitDag,
  getResolvedForkGraph,
  getResolvedUpstreamGraph,
  getResolvedRecentCommits,
  listStashes,
  createStash,
  applyStash,
  popStash,
  dropStash,
  branchFromStash,
  getStashDiff
} from './git-worktree'
export {
  checkGhInstalled,
  hasGithubRemote,
  listOpenPrs,
  getPrByUrl,
  createPr,
  getPrComments,
  addPrComment,
  mergePr,
  getPrDiff,
  getGhUser,
  editPrComment
} from './gh-cli'
export { runAiCommand } from './merge-ai'
export { listProjectRepos } from './list-project-repos'
export {
  ensureColors,
  ensureColors as ensureWorktreeColors,
  getColor as getWorktreeColor,
  getProjectColors as getProjectWorktreeColors,
  ensureProjectColors as ensureProjectWorktreeColors
} from './color-registry'
export { getGitWatcher, closeGitWatcher } from './git-watcher'
export { worktreesEvents, type WorktreesEventMap } from './events'
// Composite orchestrations + behavior resolvers shared with the IPC handlers.
export {
  detectChildRepos,
  detectWorktreesWithColors,
  resolveCopyBehavior,
  resolveSubmoduleInitBehavior,
  createWorktreeWithSetup,
  mergeWithAI,
  analyzeConflict
} from './composite-ops'
