// Server-side op surface for the tRPC `worktrees` router (transport layer).
// Re-exports the pure git/worktree operations the router wraps — same set the
// legacy `git:*` IPC handlers call. Main-process only (spawns git/gh, touches db).
export {
  isGitRepo,
  detectWorktrees,
  createWorktree,
  removeWorktree,
  runWorktreeSetupScript,
  initRepo,
  getCurrentBranch,
  listBranches,
  checkoutBranch,
  createBranch,
  hasUncommittedChanges,
  mergeIntoParent,
  abortMerge,
  startMergeNoCommit,
  isMergeInProgress,
  getConflictedFiles,
  getConflictContent,
  writeResolvedFile,
  commitFiles,
  getWorkingDiff,
  stageFile,
  unstageFile,
  discardFile,
  stageAll,
  unstageAll,
  getFileDiff,
  getUntrackedFileDiff,
  isRebaseInProgress,
  getRebaseProgress,
  abortRebase,
  continueRebase,
  skipRebaseCommit,
  getMergeContext,
  getRecentCommits,
  getAheadBehind,
  getAheadBehindUpstream,
  getStatusSummary,
  getRemoteUrl,
  gitFetch,
  gitPush,
  gitPull,
  getDefaultBranch,
  listBranchesDetailed,
  listRemoteBranches,
  getMergeBase,
  getCommitsSince,
  getCommitsBeforeRef,
  deleteBranch,
  pruneRemote,
  rebaseOnto,
  mergeFrom,
  getDiffStats,
  getWorktreeMetadata,
  getCommitDag,
  resolveChildBranches,
  copyIgnoredFiles,
  getIgnoredFileTree,
  initSubmodules,
  getResolvedCommitDag,
  getResolvedForkGraph,
  getResolvedUpstreamGraph,
  getResolvedRecentCommits,
  listStashes,
  createStash,
  applyStash,
  popStash,
  dropStash,
  branchFromStash,
  getStashDiff
} from '../main/git-worktree'
export {
  checkGhInstalled,
  hasGithubRemote,
  listOpenPrs,
  getPrByUrl,
  createPr,
  getPrComments,
  addPrComment,
  mergePr,
  getPrDiff,
  getGhUser,
  editPrComment
} from '../main/gh-cli'
export { runAiCommand } from '../main/merge-ai'
export { listProjectRepos } from '../main/list-project-repos'
export { ensureColors } from '../main/color-registry'
export { getGitWatcher } from '../main/git-watcher'
export { resolveCopyBehavior, resolveSubmoduleInitBehavior } from '../main/handlers'
